name: "Test required workflow"
on:
  pull_request
      
jobs: 
  job-always-pass:
    name: Succesful job
    runs-on: ubuntu-latest
    steps:
      - name: Always pass
        run: exit 0

  job-always-fail:
    name: Failing job
    runs-on: ubuntu-latest
    steps:
     - name: Always fail
       run: exit 1
    
  job-to-be-skipped:
     if: false
     name: Skipped job
     runs-on: ubuntu-latest
     steps:
       - name: Check out repository
         run: echo "Hello world"
